name: Markdown links verifier
on: push

jobs:
  build_and_test:
    name: Markdown links verifier
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v1

    - name: Validate links
      uses: Youssef1313/markdown-links-verifier@v0.0.2
